version: '3'
services:
  reverse-proxy:
    image: caddy:2
    ports:
      - 8000:80
    volumes:
      - ./reverse-proxy/index.html:/data/index.html
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile

  api:
    build: ./api
    # ports:
    #   - 8000:8000
    volumes:
      - type: bind
        source: ./api
        target: /app
    command: ['npx', 'nodemon', 'api.js']
